services:
  loxberry:
    build: .
    image: loxberry-arm64:latest
    container_name: loxberry
    hostname: loxberry
    restart: unless-stopped
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - loxberry_data:/opt/loxberry
    ports:
      - "8080:80"
      - "8443:443"
      - "8022:22"

volumes:
  loxberry_data: